### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by robelix** [InfluxGraph/influxgraph#52]
I'm trying to set it up with icinga2 - but I always get:

```
# gunicorn graphite_api.app:app 
[2018-04-04 18:33:27 +0000] [31596] [INFO] Starting gunicorn 19.4.5
[2018-04-04 18:33:27 +0000] [31596] [INFO] Listening at: http://127.0.0.1:8000 (31596)
[2018-04-04 18:33:27 +0000] [31596] [INFO] Using worker: sync
[2018-04-04 18:33:27 +0000] [31600] [INFO] Booting worker with pid: 31600
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
[DEBUG] 2018-04-04 18:33:28,080 - finder.__init__() - Configured aggregation functions - {<_sre.SRE_Pattern object at 0x7f1880fa82a0>: 'last', <_sre.SRE_Pattern object at 0x7f1880f9f930>: 'min', <_sre.SRE_Pattern object at 0x7f1880f9fab0>: 'sum', <_sre.SRE_Pattern object at 0x7f1880f9f9f0>: 'max'}
[INFO] 2018-04-04 18:33:28,081 - finder._start_loader() - Starting initial series list load - this may take several minutes on databases with a large number of series..
[DEBUG] 2018-04-04 18:33:28,082 - finder.get_field_keys() - Found cached field keys
[DEBUG] 2018-04-04 18:33:28,082 - finder._get_series() - Series loader calling influxdb with query - SHOW SERIES LIMIT 100000 OFFSET 0
[INFO] 2018-04-04 18:33:28,190 - finder.build_index() - Starting index build
[INFO] 2018-04-04 18:33:28,190 - finder._series_loader() - Starting background series loader with interval 900
[DEBUG] 2018-04-04 18:33:28,191 - finder.get_series() - Found cached series for limit 100000, offset 0
[DEBUG] 2018-04-04 18:33:28,192 - finder.get_field_keys() - Found cached field keys
INFO] 2018-04-04 18:33:28,192 - finder.build_index() - Building index..
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/app.py", line 68, in <module>
    configure(app)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/config.py", line 141, in configure
    finders.append(load_by_path(finder)(config))
  File "/usr/local/lib/python2.7/dist-packages/influxgraph/classes/finder.py", line 123, in __init__
    self._start_reindexer(reindex_interval)
  File "/usr/local/lib/python2.7/dist-packages/influxgraph/classes/finder.py", line 163, in _start_reindexer
    self.build_index()
  File "/usr/local/lib/python2.7/dist-packages/influxgraph/classes/finder.py", line 567, in build_index
    separator=separator)
  File "influxgraph/ext/templates.pyx", line 195, in influxgraph.ext.templates.parse_series
  File "influxgraph/ext/templates.pyx", line 84, in influxgraph.ext.templates._parse_serie_with_tags
TypeError: object of type 'NoneType' has no len()

```

Can somebody give me a hint what could cause this problem?

**Comment by pkittenis** [comment]
What is output of `show series` on influxdb? 

It looks like it is not getting anything for the name of the series. Series name is required and cannot be empty so might be bad/corrupt data in DB.

**Comment by robelix** [comment]
```
# influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.0
InfluxDB shell 0.10.0
> use icinga2
Using database icinga2
> show series;
name: ftp
---------
_key                                                    hostname                metric  service
ftp,hostname=sv22,service=ftp                           sv22                            ftp
ftp,hostname=sv22,service=ftp,metric=time               sv22                    time    ftp
ftp,hostname=sv24,service=ftp                           sv24                            ftp
ftp,hostname=sv24,service=ftp,metric=time               sv24                    time    ftp
[.... more hosts ...]


name: hostalive
---------------
_key                                                    hostname                metric
hostalive,hostname=sv22                                 sv22
hostalive,hostname=sv22,metric=pl                       sv22                    pl
hostalive,hostname=sv22,metric=rta                      sv22                    rta
hostalive,hostname=sv24                                 sv24
hostalive,hostname=sv24,metric=pl                       sv24                    pl
hostalive,hostname=sv24,metric=rta                      sv24                    rta
[.... more hosts ...]


name: http
----------
_key                                                            hostname                metric  service
http,hostname=sv22,service=http                                 sv22                            http
http,hostname=sv22,service=http,metric=size                     sv22                    size    http
http,hostname=sv22,service=http,metric=time                     sv22                    time    http
http,hostname=sv22,service=https                                sv22                            https
http,hostname=sv22,service=https,metric=size                    sv22                    size    https
http,hostname=sv22,service=https,metric=time                    sv22                    time    https
[.... more hosts ...]

[... and so on with nrpe, ping4, smtp, ssh....]

```

**Comment by pkittenis** [comment]
And the `graphite-api.yaml`? Specifically the influxdb configuration section.

**Comment by pkittenis** [comment]
Just saw the `InfluxDB shell 0.10.0` part.

Will need to upgrade to influxdb `1.0.0` at the least.

**Comment by robelix** [comment]
Thank you.

just used the default from ubuntu 1604 - going to search for a ppa...
