### ISSUE TITLE
influxgraph makes gunicorn/graphiteapi fail to start

### ISSUE THREAD

**Issue by KlavsKlavsen** [InfluxGraph/influxgraph#9]
As soon as I add influxdb finder to graphite-api.yaml, gunicorn won't start:
[2016-11-14 16:36:31 +0000] [15934] [INFO] Starting gunicorn 19.6.0
[2016-11-14 16:36:31 +0000] [15934] [INFO] Listening at: http://127.0.0.1:8080 (15934)
[2016-11-14 16:36:31 +0000] [15934] [INFO] Using worker: sync
[2016-11-14 16:36:31 +0000] [15939] [INFO] Booting worker with pid: 15939
[2016-11-14 16:36:31 +0000] [15940] [INFO] Booting worker with pid: 15940
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
/opt/graphite-api/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
/opt/graphite-api/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "/opt/graphite-api/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==19.6.0', 'console_scripts', 'gunicorn')()
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/arbiter.py", line 218, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/arbiter.py", line 331, in halt
    self.stop()
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/arbiter.py", line 381, in stop
    time.sleep(0.1)
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in handle_chld
    self.reap_workers()
  File "/opt/graphite-api/lib/python2.7/site-packages/gunicorn/arbiter.py", line 506, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

I tried putting in "full config" from your example - but still no change. switching nothing except back to whisper finder - and it works again :(

Any hints on where to look? (its a CentOS 7 box)

**Comment by pkittenis** [comment]
Can you post the full config and stderr output please. The finder is tested to work with gunicorn, in fact [the docker container uses it](https://github.com/InfluxGraph/influxgraph/blob/master/docker/graphite-api.sh#L4).

This should work without errors if installation is complete: `python -c 'from graphite_api import app'`

Installation instructions are on the main page readme.

**Comment by KlavsKlavsen** [comment]
search_index: /srv/graphiteapi_index
finders:
- influxgraph.InfluxDBFinder
  functions:
- graphite_api.functions.SeriesFunctions
- graphite_api.functions.PieFunctions

blueflood:
  urls:
    - 'http://localhost:20000'
  tenant: 1
  enable_submetrics: false
time_zone: Europe/Copenhagen
logging:
  version: 1
  disable_existing_loggers: true
  handlers:
    stdout:
      class: logging.StreamHandler
  loggers:
    graphite_api:
      handlers:
        - stdout
      propagate: true
      level: INFO
    root:
      handlers:
        - stdout
      propagate: true
      level: INFO
cache:
    type: 'filesystem'
    dir: '/tmp/graphite-api-cache'
allowed_origins:
    - '*'

**Comment by pkittenis** [comment]
Try with just the minimal config on the main page and post the output of the below.

```
finders:
  - influxgraph.InfluxDBFinder
```

`python -c 'from graphite_api import app'`

**Comment by KlavsKlavsen** [comment]
ahh - found it. when running pip install influxgraph - it helps when you do it INSIDE the virtualenv graphiteapi uses.. Sorry for bothering here :(

**Comment by pkittenis** [comment]
No worries, glad it works. Steps to replicate are usually a good way to ensure local issues are not the cause :)
